Feature/ocp4
bcgov/identity-kit-configurations pull request #7
Opened 2021-05-03 23:51 UTC by esune

Moving the work into main

2021-05-10 14:29 UTC, WadeBarnes requested changes

2021-05-10 14:29 UTC, WadeBarnes commented on jenkins/build/Jenkinsfile
> +def LIB_BRANCH = "master"
The default/main branch of this repository is `main`.  All branch references will need to be updated accordingly.

2021-05-10 17:41 UTC, esune commented on jenkins/build/Jenkinsfile
> +def LIB_BRANCH = "master"
Resolved by #8

2021-05-10 19:31 UTC, esune commented
Please merge #8 before this gets merged, a it fixes the pipeline configurations.

2021-05-11 15:59 UTC, WadeBarnes approved these changes

2021-05-11 16:00 UTC, merged